name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Lint (pre-commit) and Run Tests
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.x

        -   name: Install tools
            run: |
                python -m pip install --upgrade pip
                pip install --upgrade pre-commit pytest

        -   name: Run pre-commit checks
            run: |
                # run all configured pre-commit hooks against the repo
                pre-commit run --all-files --show-diff-on-failure

        -   name: Run tests
            run: |
                bash scripts/run_tests.sh
